version: '3.8'

services:
  postgres_db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/

volumes: 
  pgdata:      
